# Generated by Django 3.1.4 on 2020-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='static/images/room.jpeg', upload_to=''),
        ),
    ]
