# Generated by Django 2.1.4 on 2020-12-21 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(default='No details yet! Something has probably gone wrong.', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date_recieved', models.DateField(default=datetime.date.today)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('link', models.URLField(default='google.com')),
                ('location', models.CharField(default='unsorted', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='typeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Type'),
        ),
    ]
